version: '3.7'
services:
  likemyso:
    image: docker.pkg.github.com/iwpnd/likemyso/likemyso-arm
    volumes:
      - likemyso_volume:/code/
    env_file:
      - .env
    command: likemyso start
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 0 * * *
        - swarm.cronjob.skip-running=false
      restart_policy:
        condition: none

volumes:
  likemyso_volume:
